### ISSUE TITLE
Error when trying to build Multirom for Moto G4 Plus

### ISSUE THREAD

**Issue by ghost** [MR-op3/manifest#1]
I am using the mr-7.0 branch for porting Multirom to Athene (Moto G4/G4 Plus). I made the necessary changes and tried running a build. I now end up with an error like this :

`bootable/recovery/minui/graphics_overlay.cpp:268:18: error: no member named 'heap_mask' in 'ion_allocation_data'; did you mean 'heap_id_mask'?` 

My trees are located [https://github.com/yeshwanthvshenoy/android_device_motorola_athene/tree/mr-7.0](https://github.com/yeshwanthvshenoy/android_device_motorola_athene/tree/mr-7.0). I used the bacon tree as reference to bringup and bacon compiles fine. Any help will be greatly appreciated.

**Comment by Martinusbe** [comment]
https://github.com/MR-op3/android_bootable_recovery/commit/090ee5adb7d7ec2144e6fb93128c3b38afc554cd

**Comment by ghost** [comment]
@Martinusbe thanks a ton bro! 👍 you rock!! just curious as to why this is not on the mr-7.0 branch?
